FROM everco/ever-traduora:latest

ENV NODE_ENV=production

ARG TR_SECRET 
ARG RAILWAY_STATIC_URL
ARG MYSQLHOST
ARG MYSQLPORT
ARG MYSQLDATABASE
ARG MYSQLUSER
ARG MYSQLPASSWORD

ENV TR_VIRTUAL_HOST=$RAILWAY_STATIC_URL
ENV TR_DB_TYPE=mysql 
ENV TR_DB_HOST=$MYSQLHOST
ENV TR_DB_PORT=$MYSQLPORT
ENV TR_DB_DATABASE=$MYSQLDATABASE
ENV TR_DB_USER=$MYSQLUSER
ENV TR_DB_PASSWORD=$MYSQLPASSWORD


ENTRYPOINT [ "./docker-entrypoint.sh" ]
